//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangCoffee.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponUser
    {
        public int IDCouponUser { get; set; }
        public Nullable<int> IDCoupon { get; set; }
        public Nullable<int> IDDonHang { get; set; }
        public Nullable<System.DateTime> NgayDung { get; set; }
    
        public virtual Voucher Voucher { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
