//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangCoffee.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.CouponUsers = new HashSet<CouponUser>();
        }
    
        public int IDDonHang { get; set; }
        public Nullable<int> IDNhanVien { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> TongTienBill { get; set; }
        public string TinhTrang { get; set; }
        public string ThanhToan { get; set; }
        public string PTTT { get; set; }
        public string TenKH { get; set; }
        public string SDTKH { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string DiaChiKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponUser> CouponUsers { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
