//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangCoffee.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoHang
    {
        public int IDKhoHang { get; set; }
        public int IDNguyenLieu { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public int SoLuongGiao { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
