//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangCoffee.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseHisotry
    {
        public int IDHistory { get; set; }
        public int IDSanPham { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public int SoLuong { get; set; }
        public int TongTien { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
